# exception_handling
# exception_handling done in the case of unexpected error occurrence
# eg-(for error case are 8/0 will cause a excepted error



# num1=int(input('enter a number '))
# num2=int(input('enter a number '))
# try:
#     div = num1 / num2
#     print(div)
# except:
#     print('error occurred')
# finally:
#     print('inside finally')




